controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

add_asignatura:
    path: /curso/add-asignatura
    controller: App\Controller\CursoController::addAsignatura
    methods: POST

add_curso:
    path: /curso/add-curso
    controller: App\Controller\CursoController::addCurso
    methods: POST

delete_asignatura:
    path: /curso/delete-asignatura/{id}
    controller: App\Controller\CursoController::deleteAsignatura
    methods: DELETE

delete_curso:
    path: /curso/delete-curso/{id}
    controller: App\Controller\CursoController::deleteCurso
    methods: DELETE

get_cursos:
    path: /curso/get-cursos
    controller: App\Controller\CursoController::getCursos
    methods: GET

get_asignaturas:
    path: /curso/get-asignaturas
    controller: App\Controller\CursoController::getAsignaturas
    methods: GET

get_asignaturas_by_curso:
    path: /curso/get-asignaturas-by-curso/{cursoId}
    controller: App\Controller\CursoController::getAsignaturasByCursoId
    methods: GET
